### ISSUE TITLE
Interative Yex not working

### ISSUE THREAD

**Issue by SunP04** [nonamescm/yex-lang#17]
![Screenshot_2](https://user-images.githubusercontent.com/83559896/146099443-6ad626d7-9cce-44b0-bf71-a7ef8cdd1dd1.png)

Tentei rodar `yex` pelo terminal, ocorreu o erro que apareceu na screenshot.

**Comment by nonamescm** [comment]
Olá, é bem simples. Para ter acesso ao repl é necessário instalar a yex com a feature `repl`. Que não é ativada por padrão.

**Comment by nonamescm** [comment]
`cargo install --git https://github.com/nonamescm/yex-lang.git --features=repl` seria o comando correto neste caso.
