### ISSUE TITLE
Bom dia

### ISSUE THREAD

**Issue by ghost** [nonamescm/yex-lang#8]
BOM DIA? MEU AMIGO, ESTOU BATENDO PUNHETA DESDE AS CINCO DA MANHÃ, JÁ PASSEI TODOS OS CREMES POSSÍVEIS, MEU PAU TA COM O CHEIRO DE TODOS OS CREMES QUE MINHA MÃE PASSA NA PELE, TÁ COM CHEIRO DE ABACATE COM ROSAS, MELANCIA COM EUCALIPTO, FLORES DO CAMPO COM MONANGE, CACTO SILVESTRE COM ÓLEO DE COCO, MEU PAU JÁ TÁ TÃO VERMELHO Q TÁ PARECENDO QUE A CABEÇA DELE COBRIU O PAU TODO, ELE TÁ PULSANDO E LATEJANDO AQUI NA MINHA MÃO, TÁ QUASE RASGANDO AS BEIRADAS, TÁ ARDENDO MAIS QUE CU DE PROSTITUTA SOMALIANA APÓS UM DIA DE TRABALHO, JÁ GOZEI MAIS DO QUE ATOR PORNÔ NO MEIO DA SURUBA E TÁ CADA VEZ DEMORANDO MAIS A GOZAR E CADA VEZ QUE GOZA TÁ SAINDO MENOS ESPERMA DO QUE TAVA SAINDO ANTES, EU NEM DORMIR SÓ PRA FICAR BATENDO PUNHETA ATÉ MEU PAU FICAR COM CHEIRO DE PRESUNTO ENLATADO, TUDO ISSO PRA VOCÊ ME DAR BOM DIA? MEU AMIGO, BOM DIA É A PUTA QUE TE PARIU, NÃO TEM O MÍNIMO DE CONSIDERAÇÃO PELOS OUTROS ENTÃO VAI SE FODER E ENFIA ESSE SEU BOM DIA NO MEIO DO SEU CU E NO CU DE TODO MUNDO QUE RESPONDEU BOM DIA DE VOLTA PQ O ÚNICO BOM DIA AQUI VAI SER QUANDO EU ENFIAR MEU PAU NESSE SEU CU APERTADO.

**Comment by Pietro222222** [comment]
concordo sigma ja ta na 80 punheta hoje
